# Generated by Django 4.2.5 on 2023-09-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=20)),
                ('dscrp', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='Image')),
            ],
        ),
    ]
